
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int IDENT = 22;
  public static final int RBAR = 3;
  public static final int INT = 14;
  public static final int ECHO = 19;
  public static final int STAR = 8;
  public static final int LBAR = 2;
  public static final int OPRIM = 20;
  public static final int TRUE = 11;
  public static final int IF = 15;
  public static final int REC = 18;
  public static final int SEMCOL = 6;
  public static final int NUM = 21;
  public static final int COMMA = 7;
  public static final int TWOPOINTS = 10;
  public static final int EOF = 0;
  public static final int FALSE = 12;
  public static final int CONST = 16;
  public static final int error = 1;
  public static final int ARROW = 9;
  public static final int BOOL = 13;
  public static final int RPAR = 5;
  public static final int LPAR = 4;
  public static final int FUN = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBAR",
  "RBAR",
  "LPAR",
  "RPAR",
  "SEMCOL",
  "COMMA",
  "STAR",
  "ARROW",
  "TWOPOINTS",
  "TRUE",
  "FALSE",
  "BOOL",
  "INT",
  "IF",
  "CONST",
  "FUN",
  "REC",
  "ECHO",
  "OPRIM",
  "NUM",
  "IDENT"
  };
}

